name: "PR to Asana Action"
description: "GitHub action that creates an Asana task from a PR"

inputs:
  github_token:
    description: "GITHUB_TOKEN secret set automatically for actions"
    required: true
  asana_token:
    description: "Asana Personal Access Token"
    required: true
  asana_project_id:
    description: "Asana project ID for task creation"
    required: true
  asana_section_id:
    description: "Asana section ID for task creation"
    required: true
  asana_tasks_for_pr_authors:
    description: "Comma-separated list of PR authors to create tasks for"
    default: "dependabot[bot]"

runs:
  using: "node20"
  main: "dist/index.js"
